{
 "title": "DCS-Redis",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "dcs_instance_id",
    "label": "Redis实例",
    "query": "listDims($region,SYS.DCS,dcs_instance_id,dcs_instance_id)"
   },
   {
    "name": "dcs_cluster_redis_node",
    "label": "数据节点",
    "query": "listDims($region,SYS.DCS,dcs_cluster_redis_node;$dcs_instance_id,dcs_cluster_redis_node)"
   },
   {
    "name": "dcs_cluster_proxy2_node",
    "label": "Proxy节点",
    "query": "listDims($region,SYS.DCS,dcs_cluster_proxy2_node;$dcs_instance_id,dcs_cluster_proxy2_node)"
   },
   { "name": "filter", "label": "Filter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  { "title": "实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "bandwidth_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "每秒并发操作数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "instantaneous_ops",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "缓存键总数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "keys",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "流控次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "rx_controlled",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "是否存在慢日志",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "is_slow_log_exist",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "数据节点", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "cpu_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "带宽使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "bandwidth_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "每秒并发操作数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "instantaneous_ops",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "缓存键总数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "keys",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "是否存在慢日志",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "is_slow_log_exist",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "Proxy节点", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "内存利用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": " CPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "cpu_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "每秒并发操作数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "instantaneous_ops",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  }
 ]
}