{
 "title": "ECS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "instance_id",
    "label": "云服务器",
    "query": "listDims($region,SYS.ECS,instance_id,instance_id)"
   },
   { "name": "filter", "label": "Fiter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "cpu_util",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "磁盘读IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "disk_read_requests_rate",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "磁盘写IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "disk_write_requests_rate",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "虚拟机入方向PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "network_vm_pps_in",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "虚拟机出方向PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "network_vm_pps_out",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "虚拟机整机新建连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "dimstr": "instance_id,00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "network_vm_connections",
     "namespace": "SYS.ECS",
     "period": "1",
     "region": "-"
    }
   ]
  }
 ]
}