{
 "title": "RDS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "rds_cluster_id",
    "label": "MySQL实例",
    "query": "listDims($region,SYS.RDS,rds_cluster_id,null)"
   },
   { "name": "filter", "label": "Fiter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  { "title": "MySQL实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dimstr": "rds_cluster_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "dimstr": "rds_cluster_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "dimstr": "rds_cluster_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds003_iops",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  },
  {
   "title": "GaussDB实例",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds001_cpu_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds002_mem_util",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  },
  {
   "title": "Network Input Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dimstr": "gaussdb_instance_id,e5a27e42-d55f-4943-83e4-002c467f06d8",
     "filter": "average",
     "metricName": "rds004_bytes_in",
     "namespace": "SYS.RDS",
     "period": "1",
     "region": "cn-east-3"
    }
   ]
  }
 ]
}